export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const CHECKOUT_UNIT_OF_WORK = Symbol('CHECKOUT_UNIT_OF_WORK');
export const TRANSACTION_EVENT_REPOSITORY = Symbol('TRANSACTION_EVENT_REPOSITORY');
