import { HttpStatus } from '@nestjs/common';

import type { ErrorCode } from '../../domain/error-code';

export const HTTP_STATUS_BY_ERROR_CODE: Readonly<Record<ErrorCode, HttpStatus>> = {
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
  PRODUCT_NOT_FOUND: HttpStatus.NOT_FOUND,
  QUANTITY_LIMIT_EXCEEDED: HttpStatus.UNPROCESSABLE_ENTITY,
  CITY_NOT_SUPPORTED: HttpStatus.UNPROCESSABLE_ENTITY,
  DEPARTMENT_NOT_FOUND: HttpStatus.NOT_FOUND,
  CUSTOMER_NOT_FOUND: HttpStatus.NOT_FOUND,
  TRANSACTION_NOT_FOUND: HttpStatus.NOT_FOUND,
  INSUFFICIENT_STOCK: HttpStatus.CONFLICT,
  TRANSACTION_NOT_PAYABLE: HttpStatus.CONFLICT,
  PAYMENT_ALREADY_SUBMITTED: HttpStatus.CONFLICT,
  TRANSACTION_NOT_CANCELLABLE: HttpStatus.CONFLICT,
  PAYMENT_REJECTED_BY_PROVIDER: HttpStatus.UNPROCESSABLE_ENTITY,
  PAYMENT_PROVIDER_UNAVAILABLE: HttpStatus.BAD_GATEWAY,
  PAYMENT_PROVIDER_TIMEOUT: HttpStatus.GATEWAY_TIMEOUT,
  INVALID_EVENT_SIGNATURE: HttpStatus.UNAUTHORIZED,
  DELIVERY_NOT_FOUND: HttpStatus.NOT_FOUND,
  IDEMPOTENCY_KEY_REQUIRED: HttpStatus.BAD_REQUEST,
  IDEMPOTENCY_KEY_CONFLICT: HttpStatus.CONFLICT,
  IDEMPOTENCY_REQUEST_IN_PROGRESS: HttpStatus.CONFLICT,
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
};
