export const ERROR_CODES = [
  'VALIDATION_ERROR',
  'PRODUCT_NOT_FOUND',
  'QUANTITY_LIMIT_EXCEEDED',
  'CITY_NOT_SUPPORTED',
  'DEPARTMENT_NOT_FOUND',
  'CUSTOMER_NOT_FOUND',
  'TRANSACTION_NOT_FOUND',
  'INSUFFICIENT_STOCK',
  'TRANSACTION_NOT_PAYABLE',
  'PAYMENT_ALREADY_SUBMITTED',
  'TRANSACTION_NOT_CANCELLABLE',
  'PAYMENT_REJECTED_BY_PROVIDER',
  'PAYMENT_PROVIDER_UNAVAILABLE',
  'PAYMENT_PROVIDER_TIMEOUT',
  'INVALID_EVENT_SIGNATURE',
  'DELIVERY_NOT_FOUND',
  'IDEMPOTENCY_KEY_REQUIRED',
  'IDEMPOTENCY_KEY_CONFLICT',
  'IDEMPOTENCY_REQUEST_IN_PROGRESS',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
